version: 2
machine:
  hosts:
    localhost: 127.0.0.1
jobs:
  build:
    docker:
      - image: karthikiyengar/node-nightwatch
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            - dependencies-cache
      - restore_cache:
          keys:
            - dynamo-local-cache-v1
      - run:
          name: Setup CodeClimate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}
      - run:
          name: Run Tests with Coverage
          command: |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --exit-code $?
      - save_cache:
          paths:
            - dynamodblocal
          key: dynamo-local-cache-v1
workflows:
  version: 2
  package-workflow:
    jobs:
      - build